# 一行搞定判斷式
一個 if...else 判斷式再簡單，也需要四行程式碼才能完成

```python
x = 6

if x > 5:
    print("x > 5")
else:
    print("x <= 5")
    
# x > 5
```


# 一行搞定判斷式

```python
x = 6
print("x > 5") if x > 5 else print("x <= 5")
# True
```


In [1]:
x = 6
print("x > 5") if x > 5 else print("x <= 5")

x > 5


# 大量資料的運算

大量的資料是需要做分析和運算

意味著我們要學會如何有效的去處理資料

# 回顧一下串列

之前我們學會了串列（List）

今天若我需要對串列做 Element-wise（逐元）運算

也就是將串列内的**每一筆資料都做一樣的運算或操作**

從 Excel 的邏輯來理解，就是下拉的動作

而用程式語言實作，就必須要用迴圈處理


# 範例

將 `km_list` 内的每一個長度從公里換算成英里：

```python
km_list = [3, 5, 10, 21, 42.195]
mile_list = []

km_to_mile = 0.621371192

for km in km_list:
    mile_list.append(km * km_to_mile)

print(mile_list)
# [1.864113576, 3.10685596, 6.21371192, 13.048795032000001, 26.21875744644]
```


# for 迴圈雖然可以幫我們做逐元運算

但是程式碼還是過渡冗長...

In [0]:
km_list = [3, 5, 10, 21, 42.195]
mile_list = []

for km in km_list:
    mile_list.append(km /1.6)

print(mile_list)

# lambda 匿名函數

我們在寫函式 (Function) 的時候，若是遇上相對簡單的邏輯，像是把數字加上一:

```python
def plus_one(n):
    return n + 1

plus_one(100) 
# 101
```

這樣的語法就相對的有些囉嗦：

1. 沒必要為如此簡單的邏輯特別娶一個名字
2. 不管邏輯再簡單，無可避免的需要寫兩行程式碼

In [2]:
def add_one(num):
    return num+1
lst = [100,200,300,400,500]
lst1 = []
for i in lst:
    lst1.append(add_one(i))
print(lst1)

[101, 201, 301, 401, 501]


In [3]:
add1 = lambda num : num + 1
add1(100)

101

In [4]:
lst = [100,200,300,400,500]

list(map(lambda num : num+1,lst))

[101, 201, 301, 401, 501]


# lambda 匿名函數
這裡就跟各位介紹 lambda 函數，簡單來説，就是可以允許使用者**用一行程式碼搞定一個函數**:

```python
lambda 參數1, 參數2 : 算式
```

我們來試試把上面的 **plus_one** 函數轉成匿名函數： 

```python
lambda n : n + 1
# <function __main__.<lambda>(n)>
```

但是在執行之後，Python 回傳了一段我們看不懂的東西，這時，我們來試試將它放入一個變數内： 

```python
# 注意我可以把 lambda 函數賦值給一個變數
plus_one = lambda n : n + 1

# 再把變數當成函數使用
plus_one(10)
# 11
```

注意原本的寫法：

```python
def plus_one(n):
    return n + 1
```

和匿名函數的寫法：

```python
plus_one = lambda n : n + 1
```

兩者在功能上是等價的，但是匿名函數

- 不需要 def、return
- 也不需要為函數取名

# 隨堂練習


用 lambda 函數計算營業稅金額

```python
tax = lambda amount : ___________

tax(100000)
# 5000.0
```



# lambda 匿名函數
如果今天需要實作超過一個參數的 lambda 匿名函數時...

```python
bmi = lambda weight, height : weight / height ** 2
bmi(70, 1.80)
# 21.604938271604937
```

# lambda 匿名函數

背後的原理：λ演算法

[λ演算法 Wiki](https://en.wikipedia.org/wiki/Lambda_calculus)

---
# 用 lambda 函數做逐元運算

在實務上，lambda 一般都是跟 map 函數一起搭配使用，目的就是爲了能夠**用一行簡潔的程式碼做到逐元素運算**

# map 函數

若今天我需要針對一個 list 的資料做逐元運算

輸入是一個 list，得出的結果也是一個 list，在實作上就相對麻煩...

```python
items = [1, 2, 3, 4, 5]
squared = []
for i in items:
    squared.append(i**2)
```


# lambda 匿名函數
如果今天lambda 函數有超過一個參數時...

```python
bmi = lambda weight, height : weight / height ** 2
bmi(70, 1.80)
# 21.604938271604937
```

# map 函數
除了用迴圈之外，其實還可以使用 map 函數:

map(要使用的函數, 用 list 等資料結構封裝的輸入)

```python
items = [1, 2, 3, 4, 5]

# 把 items 裡面所有數字的二次方算出來
result = map(lambda x: x**2, items)
# 最後別忘了把回傳的 map 物件轉成 list
list(result)
# [1, 4, 9, 16, 25]
```


# lambda + map 函數

這樣寫的特性在於：
- `lambda x: x**2` 可以被看成是一個**用過即丟的函數，無需定義名稱**

- 在進行語法上由於結果是由多個函數拼凑起來的（很像 Excel 的公式）
- 因此這種寫法被稱爲 Functional Programming （函式程式設計）


# Functional Programming 
延申閲讀：

1. [Wikipedia](https://zh.wikipedia.org/wiki/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B)
2. [ITHome 教學](https://ithelp.ithome.com.tw/articles/10186465)

# lambda vs def 
- 在函數的邏輯比較簡單的狀況下，會讓程式碼簡潔很多
- 在處理大量的資料 (通常都是 list / array) 可以讓程式碼簡潔一些
- 對於習慣 functional programming 的人來説 (像是 R)，語法比較直覺

# 隨堂練習
用 lambda 與 map 函數算出所有在 receivables 裡的營業稅
```python
receivables = [1000, 100, 1000000, 2344550, 543000]
taxes = _________________________
```

# filter 函數

若今天你想把一個集合的資料全部都迭代過一次

以傳入的boolean function作為條件函式

迭代每一個集合的元素，並收集結果為True的元素到一個List

# filter 函數
```python
def greater_than_five(x):
    if x > 5:
        return True
    else:
        return False

data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result = filter(greater_than_five, data)
list(result)
# [6, 7, 8, 9]
```


# filter 函數

上述的範例也可以改成用 lambda 函數寫：

```python
data = [1, 2, 3, 4, 5, 6, 7, 8, 9]

list(filter(lambda n : n > 5, data))
# [6, 7, 8, 9]
```

# map() vs filter()
- map 是算出每一個集合的值 (通常使用的 function 會回傳數值)
- filter 是判斷一個集合有哪些值會被保留下來 (通常使用的 function 會回傳布林值)


# 匿名函數看似很厲害

但是對初學者來説並不直覺

---
# 串列生成式（List Comprehension）

今天我們知道上述範例最後計算的結果會是一個串列（需要封裝多筆資料）

因此，Python 就提供了串列生成式，允許開發者用簡單的程式碼做出逐元運算

---
# 串列生成式（List Comprehension）

```python
[運算式 for 項目 in 可迭代項目]
```


In [8]:
km_list = [3,5,10,21,42.195]
mile_list = []
for km in km_list:
    mile_list.append(km/1.6)
print(mile_list)

[1.875, 3.125, 6.25, 13.125, 26.371875]


In [5]:
km_list = [3,5,10,21,42.195]
[km/1.6 for km in km_list]

[1.875, 3.125, 6.25, 13.125, 26.371875]

# 串列生成式（List Comprehension）

```python
km_list = [3, 5, 10, 21, 42.195]
km_to_mile = 0.621371192
# 將 km_list 的每一筆資料逐個放入 km，在 for 左邊的運算式算出結果之後放入 mile_list
mile_list = [km * km_to_mile for km in km_list]
print(mile_list)
# [1.864113576, 3.10685596, 6.21371192, 13.048795032000001, 26.21875744644]
```


# 串列生成式（List Comprehension）

另外，若今天需要做逐元的判斷 / 比較，輸出過濾後的結果：

```python
even_numbers = []

for i in range(1, 11):
    if i % 2 == 0:
        even_numbers.append(i)

print(even_numbers)
# [2, 4, 6, 8, 10]
```

In [20]:
even_numbers = []

for i in range(1, 11):
    if i % 2 == 0:
        even_numbers.append(i)

print(even_numbers)

[2, 4, 6, 8, 10]


# 串列生成式（List Comprehension）

我們可以在串列生成式加上 `if` 判斷式

```python
even_numbers = [i for i in range(1, 11) if i % 2 == 0]
print(even_numbers)
# [2, 4, 6, 8, 10]
```

# list 的問題
- Python 的 list 無法使用 element-wise（逐元）運算
- 在不引用套件的情況下我們可以使用迴圈來處理

```python
km_list = [3, 5, 10, 21, 42.195]
km_to_mile = 0.621371192
mile_list = []

for km in km_list:
    mile_list.append(km * km_to_mile)

print(mile_list)
```

---
# list 的問題
當然，我們也可以使用 map() 和 lambda 函數來處理

```python
km_list = [3, 5, 10, 21, 42.195]
mile_list = list(map(lambda x: x * 0.621371192, km_list))
print(mile_list)
```

# 但是這樣似乎沒有簡化，反而把程式碼變得更複雜了...

# 這時就跟大家介紹一下 numpy 

[官網](https://docs.scipy.org/doc/numpy/user/quickstart.html)
- 它是 Python 語言在資料科學領域的一個重要模組，主要用於大量資料處理上
- 功能强大，語法簡單易懂
- Numpy 底層以 C 和 Fortran 語言實作，操作多重維度的陣列**效能極佳**

---
# import numpy

```python
import numpy as np
```

In [11]:
import numpy as np

# numpy 牛刀小試

```python
km_list = [3, 5, 10, 21, 42.195]
# 將一個串列轉換成一個 numpy array
km_array = np.array(km_list)
print(type(km_array))
# numpy.ndarray
```

In [19]:
import numpy as np

km_list = [3,5,10,21,42.195]

km_ary = np.array(km_list)

km_ary / 1.6

array([ 1.875   ,  3.125   ,  6.25    , 13.125   , 26.371875])

In [23]:
type(km_ary) #python最常運用在資料處理(Data Scrence)，有三大基本套件: Numpy、Pandas、Matplotlib
             #Numpy -> nddarray

numpy.ndarray

In [26]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
np.arange(10) #他會把10當成停止點

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

# numpy 牛刀小試

```python
km_list = [3, 5, 10, 21, 42.195]
km_array = np.array(km_list)
km_to_mile = 0.621371192
mile_array = km_array * km_to_mile
print(mile_array)
# [ 1.86411358  3.10685596  6.21371192 13.04879503 26.21875745]
```

# numpy.arange() 方法

功能與 `range()` 函數相同，宣告一個數字的範圍

```python
import numpy as np

arr1 = np.arange(10)
print(arr1)
arr2 = np.arange(1, 10)
print(arr2)
arr3 = np.arange(1, 10, 2)
print(arr3)
# [0 1 2 3 4 5 6 7 8 9]
# [1 2 3 4 5 6 7 8 9]
# [1 3 5 7 9]
```


# 提取單筆資料

語法與 Python 串列一樣，透過指定索引值

```python
arr = np.array([1,2,3])
arr[0]
# 1
```

In [31]:
arr = np.array([1,2,3])
arr[1]

2

# 切片（Slicing）

```python
arr1 = np.arange(0, 10)
print(arr1)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1[1:3]
# array([1, 2])
```

# 切片（Slicing）

```python
arr1 = np.arange(0, 10)
print(arr1)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1[5:]
# array([5, 6, 7, 8, 9])
```

# 切片（Slicing）

```python
arr1 = np.arange(0, 10)
arr1[:5]
# array([0, 1, 2, 3, 4])
```


# numpy 更新資料功能

```python
arr1 = np.arange(0, 10)
arr1[2] = 8
print(arr1)
# array([0, 1, 8, 3, 4, 5, 6, 7, 8, 9])
```


# numpy 刪除資料功能

```python
arr1 = np.arange(0, 10)
print(np.delete(arr1, 1))
# array([0, 2, 3, 4, 5, 6, 7, 8, 9])
```

# numpy 刪除資料功能

```python
arr1 = np.arange(0, 10)
print(np.delete(arr1, slice(0, 5)))
# array([5, 6, 7, 8, 9])
```

# ndArray 與 ndArray 的運算

```python
arr2 = np.arange(5)
# array([0, 1, 2, 3, 4])
arr3 = np.arange(2, 12, 2)
# array([1., 2., 3., 4., 5.])
```

In [35]:
arr2 = np.arange(5)
print(arr2)
arr3 = np.arange(2,12,2)
print(arr3)

print(arr2+arr3)

[0 1 2 3 4]
[ 2  4  6  8 10]
[ 2  5  8 11 14]


# ndArray 與 ndArray 的運算

```python
arr3 / 2
# array([1., 2., 3., 4., 5.])
```

# ndArray 與 ndArray 的運算

```python
arr2 + arr3
# array([ 2,  5,  8, 11, 14])
```

# ndArray 與 ndArray 的運算

```python
arr2 - arr3
# array([-2, -3, -4, -5, -6])
```

# ndArray 與 ndArray 的運算

```python
arr2 * arr3
# array([ 0,  4, 12, 24, 40])
```

# ndArray 與 ndArray 的運算

```python
arr2 / arr3
# array([0.        , 0.25      , 0.33333333, 0.375     , 0.4       ])
```


# 隨堂練習

- 請用 numpy 練習計算這五個人的 BMI
- 回傳的多筆 bmi 值必須是一個陣列
```python
heights = [173, 168, 171, 189, 179]
weights = [65.4, 59.2, 63.6, 88.4, 68.7]
```

In [42]:
import numpy as np

heights = [173, 168, 171, 189, 179]  #python list
weights = [65.4, 59.2, 63.6, 88.4, 68.7]

H = np.array(heights)
W = np.array(weights)

print(W / (H/100)**2)


[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


# 多維串列

若今天我們想透過 Python 的資料結構表達一個矩陣（Matrix）

![](https://drive.google.com/uc?export=download&id=1guRahErsyffNPtrix__hXtsno9158HpQ)

這就有一點麻煩了，因爲矩陣的資料雖然是有序的，但是矩陣**不會只有一個維度**，若是用 Python 的串列表示，是無法把維度的概念表達出來的

---
# 多維串列

Python 可以在一個串列内放入一個或多個串列：

```python
matrx = [[1, 2],[3, 4],[5, 6]]
```


In [50]:
matrx = [[1, 2],[3, 4],[5, 6]]
print(matrx)
print(matrx[1])
print(matrx[1][1])

[[1, 2], [3, 4], [5, 6]]
[3, 4]
4


# 多維串列

把它展開來看:

```python
matrx = [
            [1, 2],
            [3, 4],
            [5, 6]
        ]
```

就會發現這種巢狀串列很適合用來表達類似像是矩陣的多維資料，内部的三個串列，代表矩陣的一行 (Row)，相對的，當三行曡起來時，就是一個縱向、寬度為 2 的欄 (Column)

![](https://drive.google.com/uc?export=download&id=1GTTq1Nl_RjFFVI08A-NYoZBkTYtlvi5P)

# 多維串列

一般我們在表達多維串列大小的方式，**與表達矩陣大小的方式是一樣的**，下面的範例程式碼就是在宣告一個 3 x 2 的多維串列

```python
matrx = [
            [1, 2],
            [3, 4],
            [5, 6]
        ]
```


# 提取多維串列的資料

今天若需要讀取多維串列内的值

```python
matrx[第一維的索引值, 第二維的索引值]
```

# 提取多維串列串列的資料

今天若需要讀取多維串列内的值

```python
matrx[0]
# [1, 2]

matrx[0][1]
# 2
```


# Nested Loop （巢狀迴圈）

若要將多維串列内的每一個元素都遍歷一次，可以用巢狀迴圈，也就是在迴圈内再寫一個迴圈

```python
for i in range(0, 3):
    for j in range(0, 2):
        print(matrx[i][j])
```

# np 對多維串列的支援

```python
arr = np.arange(1, 7)
arr
# array([1, 2, 3, 4, 5, 6])
```


In [53]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

# np.reshape()

改變一個 ndArray 的形狀，可以將每一個維度的大小依序放入參數：

```python
arr.reshape(3, 2)

#array([[1, 2],
#       [3, 4],
#       [5, 6]])
```


In [54]:
arr.reshape(3,2) #和矩陣同 -> 先高再寬

array([[1, 2],
       [3, 4],
       [5, 6]])

# np.shape

檢查一個 ndArray 的大小

```python
arr1 = arr.reshape(4,3)
arr1.shape
# (4, 3)
```

In [55]:
arr1 = np.arange(12)
arr1 = arr1.reshape(4,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# 多維 ndArray 的切片

```python
arr1[:2]
# array([[0, 1, 2],
#        [3, 4, 5]])
```


In [57]:
print(arr1[:2])

[[0 1 2]
 [3 4 5]]


# 多維 ndArray 的切片

```python
arr1[:2]
# array([[0, 1, 2],
#        [3, 4, 5]])
```

In [58]:
print(arr1[2:])

[[ 6  7  8]
 [ 9 10 11]]


# 多維 ndArray 的切片

```python
arr4[2:]
# array([[ 6,  7,  8],
#        [ 9, 10, 11]])
```

# 多維 ndArray 的切片

```python
arr4[2:,1:]
# array([[ 7,  8],
#        [10, 11]])
```

In [60]:
print(arr1)
print(arr1[2:,1:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 7  8]
 [10 11]]


# np.zeros

```python
np.zeros((3,2))
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])
```

# np.ones

```python
np.ones((3,4))
# array([[1., 1., 1., 1.],
#        [1., 1., 1., 1.],
#        [1., 1., 1., 1.]])
```


# 補充

有興趣的可以參考到 Numpy 的官方文件做進一步的學習。

官方教學：[https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)

Github 專案：[https://github.com/numpy/numpy](https://github.com/numpy/numpy)

